### ISSUE TITLE
triggerUncaughtException when starting project

### ISSUE THREAD

**Issue by LevequeFra** [dassschaf/nextcontrol#8]
Hi,

First of all many thanks for this project !

Port from code is hardcoded, so the config file does not very useful. 
But i spend long time to understand (without .catch log) why nextcontrol doesn't want to start. Just because i have an other dedicated server running in deamon (with different ports) ...

See you ;)

**Comment by dassschaf** [comment]
Heyo, thanks for reporting that issue - I have absolutely missed that when introducing the settings file. 🤦 

I just pushed a fix for that, it should work as intended now!
